web:
  restart: always
  build: ./app
  expose:
    - "5000"
  links:
    - mysql:mysql
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn app:application -w 2 -b :5000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

mysql:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=flask
    - MYSQL_ROOT_PASSWORD=zaq12wsx
  ports:
    - "3306:3306"